language: node_js
node_js:
  - "node"
services:
  - docker
before_script:
  - ./bin/faktory -d
  - |
    until nc -z -v -w30 127.0.0.1 7419
    do
      sleep 1
    done
script:
- npm test
after_success:
- cat ./node_modules/lcov.info | ./node_modules/coveralls/bin/coveralls.js
